---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management
  labels:
    app: customer-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      labels:
        app: customer-management
    spec:
      containers:
        - name: customer-management
          image: username/customer-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-management
  labels:
    app: account-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-management
  template:
    metadata:
      labels:
        app: account-management
    spec:
      containers:
        - name: account-management
          image: username/account-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: customer-management
  labels:
    app: customer-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-management


---


apiVersion: v1
kind: Service
metadata:
  name: account-management
  labels:
    app: account-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: account-management

